In [1]:
#importing math library
import math
A=16
print(math.sqrt(A))

4.0


In [3]:
#import methods in python
#Using sqrt and sin methods from python library
from math import sqrt,sin
A=16
B=3.14
print(sqrt(A))
print(sin(B))

4.0
0.0015926529164868282


In [4]:
import numpy as np
np.sqrt([2,4,9,16])

array([1.41421356, 2.        , 3.        , 4.        ])

In [5]:
from numpy import pi
np.cos(0)

1.0

In [6]:
np.sin(pi/2)

1.0

In [7]:
np.cos(pi)

-1.0

In [8]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [9]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [10]:
#numpy rearrangement of arrays
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [12]:
#ravels method will merge the different arrays into one.
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [13]:
#reshape method converts single array into 3*4 matrix
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [15]:
#resize method converts back into 2*6 matrix
new_cyclist_trials.resize(2,6)
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [16]:
#hsplit method splits 2*6 array into two 2*3 arrays
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [17]:
new_cyclist_1 = np.array([10,15,17,26,13,19])
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [19]:
#hstack method stacks two arrays into one.
np.hstack((new_cyclist_1,new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [20]:
import numpy as np
first_numpy_array = np.array([1,2,3,4])
print(first_numpy_array)

[1 2 3 4]


In [22]:
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#reshape method to change/create array
np_arange = np.arange(12)
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
#linspace for linear equally spaced data elements
np_linspce = np.linspace(1,6,5)
np_linspce

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [38]:
#One dimensional array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
#Two Dimensional Array
TwoD_array = oneD_array.reshape(3,5)
TwoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
#Three Dimensional Array
ThreeD_array = np.arange(27).reshape(3,3,3)
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])